cheat_entry_delay_in_seconds: 0.25
countdown_in_seconds: 5
should_echo_cheat_entry_in_cmd: true
cheats_to_enter:
  - "moveObjects on"
  - "disableSnappingToSlotsOnAlt on"
  - "testingCheatsEnabled true"
  - "movieMakerCheatsEnabled true"
  - "hideHeadlineEffects on"
  - "fadeObjects off"
  - "BuyDebug true"