delay_between_cheats_in_seconds: 0.25
countdown_in_seconds: 10
should_auto_open_window: true
window_name: 'the sims 3'
cheats_to_enter:
  - "moveObjects on"
  - "disableSnappingToSlotsOnAlt on"
  - "testingCheatsEnabled true"
  - "movieMakerCheatsEnabled true"
  - "hideHeadlineEffects on"
  - "fadeObjects off"
  - "BuyDebug true"